import { z } from "zod";
import { tool } from "ai";
import { GoogleGenAI } from "@google/genai";
import { uploadImageToR2 } from "@/lib/storage/r2";
import {
  GoogleApiKeyPool,
  loadGoogleApiKeysFromEnv,
} from "@/lib/gemini/api-key-pool";
import { retryWithBackoff } from "@/lib/utils/retry";

// Dedicated instance for image generation
const imageApiKeyPool = new GoogleApiKeyPool(loadGoogleApiKeysFromEnv());

export const generateMarketingPosterTool = tool({
  description:
    "Generate a marketing poster, WhatsApp status creative, or ad banner based on a detailed visual prompt. Returns the permanent public URL of the generated image.",
  parameters: z.object({
    visual_prompt: z
      .string()
      .optional()
      .describe(
        "A highly detailed visual prompt for the poster, including business details, text placement, demographic requirements, and scene description.",
      ),
    prompt: z.string().optional().describe("Fallback for the visual prompt."),
  }),
  execute: async (args: { visual_prompt?: string; prompt?: string }) => {
    const finalPrompt = args.visual_prompt || args.prompt;
    if (!finalPrompt) return "Error: You must provide a visual prompt.";
    try {
      const apiKey = imageApiKeyPool.acquire();
      if (!apiKey) {
        return "Error: No Gemini API key available in the pool.";
      }

      // Initialize the official Google GenAI SDK
      const ai = new GoogleGenAI({ apiKey });

      // Create timeout abort controller
      const abortController = new AbortController();
      const timeoutId = setTimeout(() => abortController.abort(), 45000); // 45s

      let response;
      try {
        response = await ai.interactions.create({
          model: "gemini-3.1-flash-lite-image",
          input: finalPrompt,
          response_format: {
            type: "image",
            image_size: "1K",
          },
        });
      } catch (err) {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const error = err as any;

        // Handle timeout
        if (abortController.signal.aborted) {
          return "Error: Image generation timed out after 45 seconds. Please try again with a simpler prompt.";
        }

        // Handle rate limiting
        if (error?.status === 429 || error?.message?.includes("429")) {
          imageApiKeyPool.markRateLimited(apiKey);
          return "Error: Rate limit reached. Please try again in a few moments.";
        }

        // Handle 500 Internal Server Error
        if (
          error?.status === 500 ||
          error?.message?.includes("500") ||
          error?.message?.includes("Internal Server Error")
        ) {
          return "Error: The image generation service is currently experiencing technical difficulties. Please try again later.";
        }

        // Handle 404 Not Found (e.g. Model not found)
        if (
          error?.status === 404 ||
          error?.message?.includes("404") ||
          error?.message?.includes("not found")
        ) {
          return "Error: The image generation model required for this task is currently unavailable. Please contact support.";
        }

        throw error;
      } finally {
        clearTimeout(timeoutId);
      }

      const generatedImage = response.output_image;
      if (!generatedImage) {
        throw new Error("No image was generated by the API.");
      }

      const base64Data = generatedImage.data;
      if (!base64Data) {
        throw new Error("No image data returned from API.");
      }

      // Upload to R2
      const filename = `marketing-tool-${Date.now()}.webp`;
      const publicUrl = await retryWithBackoff(
        () => uploadImageToR2(base64Data, filename),
        {
          maxRetries: 3,
          shouldRetry: (error) => {
            if (
              error instanceof Error &&
              error.message.includes("Missing R2 configuration")
            ) {
              return false;
            }
            return true;
          },
        },
      );

      return `Image successfully generated and persisted. You MUST display it to the user using this EXACT markdown format: ![Generated Poster](${publicUrl})`;
    } catch (e: unknown) {
      return `Error generating marketing poster: ${e instanceof Error ? e.message : String(e)}`;
    }
  },
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
} as any);
